---
# Secret configure password for mysql Cluster
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    app: mysql
type: Opaque
data:
  password: root # echo -n 'uUN38#%pq' |base64
